name: 'Setup and Run'
description: 'Common setup and execution steps'

inputs:
  script-name:
    description: 'Name of the script/task'
    required: true
  command:
    description: 'Command to run'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - run: npm ci
      shell: bash

    - run: mkdir -p ci-artifacts
      shell: bash

    - name: Run ${{ inputs.script-name }}
      shell: bash
      run: |
        set -o pipefail
        set -e

        echo "Running command:"
        echo "${{ inputs.command }}"

        bash -e <<'EOF' 2> "ci-artifacts/${{ inputs.script-name }}-stderr.log"
        ${{ inputs.command }}
        EOF

        echo '{"ok": true, "name": "${{ inputs.script-name }}"}' \
          > ci-artifacts/${{ inputs.script-name }}-status.json

      continue-on-error: false

    - name: Handle failure
      if: failure()
      shell: bash
      run: |
        if [ -f "ci-artifacts/${{ inputs.script-name }}-stderr.log" ]; then
          LAST_ERROR_LINE=$(tail -1 "ci-artifacts/${{ inputs.script-name }}-stderr.log" | sed 's/"/\\"/g' | tr -d '\n')
          
          if [ -n "$LAST_ERROR_LINE" ]; then
            ERROR_OUTPUT="$LAST_ERROR_LINE"
          else
            ERROR_OUTPUT="Command failed for ${{ inputs.script-name }}"
          fi
        else
          ERROR_OUTPUT="Command failed for ${{ inputs.script-name }} (no stderr available)"
        fi

        echo "{\"ok\": false, \"error\": \"$ERROR_OUTPUT\"}" \
          > ci-artifacts/${{ inputs.script-name }}-status.json

        exit 1

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.script-name }}-status
        path: ci-artifacts/
